"""Changed relationship between 'Section' and 'Project' models

Revision ID: 19b87dbdf9f1
Revises: 72a47fa9c93b
Create Date: 2024-09-01 14:30:51.157802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b87dbdf9f1'
down_revision = '72a47fa9c93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sections', ['section_id'], ['id'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint('sections_project_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('sections_project_id_fkey', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('section_id')

    # ### end Alembic commands ###
