"""Added 'Project' model

Revision ID: 59375d9897fe
Revises: 4d34156a82ba
Create Date: 2024-09-01 13:33:07.206954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59375d9897fe'
down_revision = '4d34156a82ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('sort_in_list', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('cover_proj', sa.String(length=256), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
