"""Removed field 'num_projects' from 'Section' model

Revision ID: 64cd94b65bd6
Revises: 1ee1c86b6a5c
Create Date: 2024-08-15 14:39:24.224422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cd94b65bd6'
down_revision = '1ee1c86b6a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('num_projects')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_projects', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
