"""Added new column 'season_type' for 'Project' model

Revision ID: a61042be53b1
Revises: fe8c91b690e0
Create Date: 2024-09-06 11:26:00.951326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61042be53b1'
down_revision = 'fe8c91b690e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('season_type')

    # ### end Alembic commands ###
