"""Renamed field 'cover_img' to 'cover_proj' in 'Section' model

Revision ID: b4b8c515b353
Revises: 64cd94b65bd6
Create Date: 2024-08-15 14:44:05.288327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b8c515b353'
down_revision = '64cd94b65bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_proj', sa.String(length=256), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('cover_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_img', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('cover_proj')

    # ### end Alembic commands ###
