"""empty message

Revision ID: ecf2f7d68d5b
Revises: ca8180af23ce
Create Date: 2024-09-01 15:16:34.714088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf2f7d68d5b'
down_revision = 'ca8180af23ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=256), nullable=True))
        batch_op.create_unique_constraint(None, ['slug'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
