"""Added new model -> 'Panorama'

Revision ID: fe8c91b690e0
Revises: ecf2f7d68d5b
Create Date: 2024-09-05 14:29:16.257348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe8c91b690e0'
down_revision = 'ecf2f7d68d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('panorama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('sort_in_list', sa.Integer(), nullable=True),
    sa.Column('cover_proj', sa.String(length=256), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_panorama'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('panorama')
    # ### end Alembic commands ###
